---
stages:
  - setup
  - lint
  - pull
  - test
  - deploy
  - docker

.test_template: &test_tpl
  stage: test
  dependencies:
    - setup
  image:
    name: esphome/esphome:$ESPHOME_VERSION
    entrypoint: [""]
  rules:
    - changes:
        - $file
        - .ESPHOME_VERSION
  script:
    - mv $CI_PROJECT_DIR/fake_secrets.yaml $CI_PROJECT_DIR/secrets.yaml
    - esphome compile $CI_PROJECT_DIR/$file

setup:
  stage: setup
  artifacts:
    reports:
      dotenv: init.env
  script:
    - echo -n "ESPHOME_VERSION=" | cat - .ESPHOME_VERSION >> init.env

lint yaml:
  stage: lint
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

pull docker image:
  stage: pull
  dependencies:
    - setup
  image:
    name: esphome/esphome:$ESPHOME_VERSION
    entrypoint: [""]
  rules:
    - changes:
        - .ESPHOME_VERSION
  script:
    - esphome version

test boiler_keuken:
  variables:
    file: boiler_keuken.yaml
  <<: *test_tpl
test bureau:
  variables:
    file: bureau.yaml
  <<: *test_tpl
test cv:
  variables:
    file: cv.yaml
  <<: *test_tpl
test kantoor_plant:
  variables:
    file: kantoor_plant.yaml
  <<: *test_tpl
test meterkast:
  variables:
    file: meterkast.yaml
  <<: *test_tpl
test nas:
  variables:
    file: nas.yaml
  <<: *test_tpl
test tv:
  variables:
    file: tv.yaml
  <<: *test_tpl
test vloerverwarming:
  variables:
    file: vloerverwarming.yaml
  <<: *test_tpl
test wasmachine:
  variables:
    file: wasmachine.yaml
  <<: *test_tpl

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "**/*.yaml"
        - .ESPHOME_VERSION
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - sh ./build/deploy.sh

docker:
  stage: docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - .ESPHOME_VERSION
  trigger: koen/docker
