stages:
  - init
  - test
  - deploy
  - docker

init:
  stage: init
  artifacts:
    reports:
      dotenv: init.env
  script: 
    - echo -n "ESPHOME_VERSION=" | cat - .ESPHOME_VERSION >> init.env

test:
  stage: test
  dependencies:
    - init
  image:
    name: esphome/esphome:$ESPHOME_VERSION
    entrypoint: [""]
  script:
    - sh ./build/test.sh

deploy:
  stage: deploy
  only:
    - master
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - sh ./build/deploy.sh

docker:
  stage: docker
  only:
    refs:
      - master
    changes:
      - .ESPHOME_VERSION
  trigger: koen/docker
