stages:
  - init
  - test
  - deploy
  - docker

init:
  stage: init
  artifacts:
    reports:
      dotenv: init.env
  script: 
    - echo -n "ESPHOME_VERSION=" | cat - .ESPHOME_VERSION >> init.env

test:
  stage: test
  dependencies:
    - init
  image:
    name: esphome/esphome:$ESPHOME_VERSION
    entrypoint: [""]
  script:
    - sh ./build/test.sh

deploy:
  stage: deploy
  only:
    - master
  script:
    # https://unix.stackexchange.com/a/417661
    - apk update && apk add openssh sshpass
    - sh ./build/deploy.sh

docker:
  stage: docker
  only:
    refs:
      - master
    changes:
      - .ESPHOME_VERSION
  trigger: koen/docker
