esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: ${display_name} Hotspot
    password: !secret ap_password

api:
  password: !secret api_password

ota:
  password: !secret ota_password

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

interval:
- interval: 10s
  then:
    if:
      condition:
        wifi.connected:
      then:
      - switch.turn_on: blue_led
      else:
      - switch.turn_off: blue_led

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
  name: ${display_name} Power Button
  on_press:
  - switch.toggle: relay

- platform: status
  name: ${display_name} Status

switch:
- platform: gpio
  id: blue_led
  pin:
    number: GPIO13
    inverted: true

- platform: gpio
  name: ${display_name}
  pin: GPIO12
  id: relay
  icon: ${icon}
  restore_mode: ${restore_mode}

- platform: restart
  name: ${display_name} Restart

sensor:
- platform: wifi_signal
  name: ${display_name} WiFi Signal
  update_interval: 60s
  filters:
  - sliding_window_moving_average:
      window_size: 15
      send_every: 15
      send_first_at: 1

- platform: cse7766
  update_interval: 15s
  current:
    name: ${display_name} Current
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
        send_first_at: 1
  voltage:
    name: ${display_name} Voltage
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
        send_first_at: 1
  power:
    name: ${display_name} Current Consumption
    id: ${device_id}_wattage
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
        send_first_at: 1

- platform: total_daily_energy
  name: ${display_name} Today's Consumption
  power_id: ${device_id}_wattage
  filters:
  - multiply: 0.001
  unit_of_measurement: kWh

time:
- platform: homeassistant
  id: homeassistant_time
