esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: "${template_variables_name} Hotspot"
    password: !secret ap_password

api:
  password: !secret api_password

ota:
  password: !secret ota_password

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

interval:
- interval: 10s
  then:
    if:
      condition:
        wifi.connected:
      then:
      - switch.turn_on: blue_led
      else:
      - switch.turn_off: blue_led

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
  name: "${template_variables_name} Power Button"
  on_press:
  - switch.toggle: relay

- platform: status
  name: "${template_variables_name} Status"

switch:
- platform: gpio
  id: blue_led
  pin:
    number: GPIO13
    inverted: true

- platform: gpio
  name: "${template_variables_name}"
  pin: GPIO12
  id: relay
  icon: ${template_variables_icon}
  restore_mode: RESTORE_DEFAULT_OFF

- platform: restart
  name: "${template_variables_name} Restart"

sensor:
- platform: wifi_signal
  name: "${template_variables_name} WiFi Signal"
  update_interval: 60s
  filters:
  - sliding_window_moving_average:
      window_size: 15
      send_every: 15
      send_first_at: 1

- platform: cse7766
  update_interval: 15s
  current:
    name: "${template_variables_name} Current"
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
        send_first_at: 1
  voltage:
    name: "${template_variables_name} Voltage"
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
        send_first_at: 1
  power:
    name: "${template_variables_name} Current Consumption"
    id: ${template_variables_name}_wattage
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
        send_first_at: 1

- platform: total_daily_energy
  name: "${template_variables_name} Today\'s Consumption"
  power_id: ${template_variables_name}_wattage
  filters:
  - multiply: 0.001
  unit_of_measurement: kWh

time:
- platform: homeassistant
  id: homeassistant_time
